add edge dependency to podspec
adobe/aepsdk-edgeconsent-ios pull request #43
Opened 2021-06-30 21:52 UTC by sbenedicadb

2021-06-30 21:52 UTC, nporter-adbe approved these changes

2021-06-30 22:38 UTC, emdobrin reviewed
Thanks! can we add it to package.swift too?

2021-06-30 22:38 UTC, emdobrin commented on AEPEdgeConsent.podspec
> +  s.dependency 'AEPEdge', '>= 1.1.1'
it required min 1.1.0

2021-07-01 15:46 UTC, sbenedicadb commented
@emdobrin done!

2021-07-01 18:12 UTC, emdobrin commented on Package.swift
> +        .package(url: "https://github.com/adobe/aepsdk-core-ios.git", .branch("main")),
let's update this one as well to .upToNextMajor(from: "3.1.0"))

2021-07-01 18:41 UTC, emdobrin approved these changes

2021-07-12 17:53 UTC, kevinlind requested changes
Can you update the README.md similar to this PR? https://github.com/adobe/aepsdk-edgeidentity-ios/pull/42

2021-07-12 17:53 UTC, kevinlind commented on Package.swift
>          .testTarget(name: "FunctionalTests",
Let's remove the test targets here.

2021-07-12 21:48 UTC, kevinlind approved these changes

2021-07-12 21:48 UTC, merged